export const filtersRef = [
  {
    name: "original",
    src:
      "https://github.com/EXTC27/ai-pjt/blob/master/imgs/original.jpg?raw=true",
    blur: 0,
    hue: 0,
    saturation: 0,
    luminance: 0,
    contrast: 0,
  },
  {
    name: "daily",
    src: "https://github.com/EXTC27/ai-pjt/blob/master/imgs/daily.jpg?raw=true",
    hue: 1,
    saturation: 0.16,
    luminance: 0.1,
    blur: 0,
    contrast: 2,
  },
  {
    name: "light",
    src: "https://github.com/EXTC27/ai-pjt/blob/master/imgs/light.jpg?raw=true",
    hue: 0,
    saturation: 0.18,
    luminance: 0.08,
    blur: 0,
    contrast: 0,
  },
  {
    name: "plain",
    src: "https://github.com/EXTC27/ai-pjt/blob/master/imgs/plain.jpg?raw=true",
    hue: 3.8,
    saturation: 0.08,
    luminance: 0.06,
    blur: 0,
    contrast: 0,
  },

  {
    name: "cream",
    src: "https://github.com/EXTC27/ai-pjt/blob/master/imgs/cream.jpg?raw=true",

    hue: 0,
    saturation: 0.18,
    luminance: 0.19,
    blur: 0,
    contrast: 0,
  },

  {
    name: "pure",

    src: "https://github.com/EXTC27/ai-pjt/blob/master/imgs/pure.jpg?raw=true",
    hue: 0,
    saturation: 0.04,
    luminance: 0.13,
    blur: 0,
    contrast: 0,
  },
  {
    name: "grayscale",
    src:
      "https://github.com/EXTC27/ai-pjt/blob/master/imgs/grayscale.jpg?raw=true",
    hue: 0,
    saturation: -5,
    luminance: -0.03,
    blur: 0,
    contrast: 0,
  },
  {
    name: "BS",
    src: "https://github.com/EXTC27/ai-pjt/blob/master/imgs/BS.jpg?raw=true",
    hue: 0,
    saturation: -0.13,
    luminance: 0.06,
    blur: 0,
    contrast: 0,
  },
  {
    name: "frozen",
    src:
      "https://github.com/EXTC27/ai-pjt/blob/master/imgs/frozen.jpg?raw=true",
    hue: 3.8,
    saturation: -0.38,
    luminance: 0.11,
    blur: 0,
    contrast: 0,
  },
  {
    name: "pretty",
    src:
      "https://github.com/EXTC27/ai-pjt/blob/master/imgs/pretty.jpg?raw=true",
    hue: 1.6,
    saturation: 0.09,
    luminance: 0.04,
    blur: 0,
    contrast: 10,
  },

  {
    name: "milk",
    src: "https://github.com/EXTC27/ai-pjt/blob/master/imgs/milk.jpg?raw=true",
    hue: 0,
    saturation: -0.21,
    luminance: -0.01,
    blur: 0,
    contrast: 0,
  },
  {
    name: "crystal",
    src:
      "https://github.com/EXTC27/ai-pjt/blob/master/imgs/crystal.jpg?raw=true",
    hue: 0,
    saturation: 0.04,
    luminance: 0.03,
    blur: 0,
    contrast: 0,
  },
  {
    name: "cloud",
    src: "https://github.com/EXTC27/ai-pjt/blob/master/imgs/cloud.jpg?raw=true",
    hue: 0,
    saturation: 0,
    luminance: -0.13,
    blur: 0,
    contrast: 0,
  },
  {
    name: "mood",
    src: "https://github.com/EXTC27/ai-pjt/blob/master/imgs/mood.jpg?raw=true",
    hue: 0,
    saturation: -0.04,
    luminance: -0.06,
    blur: 0,
    contrast: 0,
  },
  {
    name: "loveletter",
    src:
      "https://github.com/EXTC27/ai-pjt/blob/master/imgs/loveletter.jpg?raw=true",
    hue: 6.4,
    saturation: 0.21,
    luminance: 0.06,
    blur: 0,
    contrast: 0,
  },
  {
    name: "baby",
    src: "https://github.com/EXTC27/ai-pjt/blob/master/imgs/baby.jpg?raw=true",
    hue: 1.3,
    saturation: 0.21,
    luminance: 0.04,
    blur: 0,
    contrast: 0,
  },
  {
    name: "momo",
    src: "https://github.com/EXTC27/ai-pjt/blob/master/imgs/momo.jpg?raw=true",
    hue: 0,
    saturation: 0.47,
    luminance: 0.13,
    blur: 0,
    contrast: 0,
  },
  {
    name: "winter",
    src:
      "https://github.com/EXTC27/ai-pjt/blob/master/imgs/winter.jpg?raw=true",
    hue: 0,
    saturation: -0.34,
    luminance: 0.2,
    blur: 0,
    contrast: 26,
  },
  {
    name: "retro",
    src: "https://github.com/EXTC27/ai-pjt/blob/master/imgs/retro.jpg?raw=true",
    hue: 6.4,
    saturation: -0.07,
    luminance: 0.19,
    blur: 0,
    contrast: 3,
  },
  {
    name: "alight",
    src:
      "https://github.com/EXTC27/ai-pjt/blob/master/imgs/alight.jpg?raw=true",
    hue: 9.7,
    saturation: 0.46,
    luminance: 0.15,
    blur: 0,
    contrast: 8,
  },
  {
    name: "aurora",
    src:
      "https://github.com/EXTC27/ai-pjt/blob/master/imgs/aurora.jpg?raw=true",
    hue: 0,
    saturation: -0.09,
    luminance: -0.03,
    blur: 0,
    contrast: 23,
  },
  {
    name: "vintage",
    src:
      "https://github.com/EXTC27/ai-pjt/blob/master/imgs/vintage.jpg?raw=true",
    hue: 12.1,
    saturation: -0.22,
    luminance: -0.07,
    blur: 0,
    contrast: 16,
  },
  {
    name: "yummy",
    src: "https://github.com/EXTC27/ai-pjt/blob/master/imgs/yummy.jpg?raw=true",
    hue: 0,
    saturation: 0.38,
    luminance: -0.18,
    blur: 0,
    contrast: 0,
  },
  {
    name: "natural",
    src:
      "https://github.com/EXTC27/ai-pjt/blob/master/imgs/natural.jpg?raw=true",
    hue: 0,
    saturation: 0.18,
    luminance: 0.2,
    blur: 0,
    contrast: 12,
  },

  {
    name: "drama",
    src: "https://github.com/EXTC27/ai-pjt/blob/master/imgs/drama.jpg?raw=true",
    hue: 4.8,
    saturation: -3.38,
    luminance: 0.17,
    blur: 0,
    contrast: 17,
  },
  {
    name: "cute",
    src: "https://github.com/EXTC27/ai-pjt/blob/master/imgs/cute.jpg?raw=true",
    hue: 0,
    saturation: -0.12,
    luminance: 0.12,
    blur: 0,
    contrast: -1,
  },

  {
    name: "midnight",
    src:
      "https://github.com/EXTC27/ai-pjt/blob/master/imgs/midnight.jpg?raw=true",
    hue: 8.9,
    saturation: 0.66,
    luminance: -0.12,
    blur: 0,
    contrast: -15,
  },
  {
    name: "blossom",
    src:
      "https://github.com/EXTC27/ai-pjt/blob/master/imgs/blossom.jpg?raw=true",
    hue: 2.4,
    saturation: -0.18,
    luminance: 0.11,
    blur: 0,
    contrast: 24,
  },
  {
    name: "night",
    src: "https://github.com/EXTC27/ai-pjt/blob/master/imgs/night.jpg?raw=true",
    hue: 5.6,
    saturation: -0.39,
    luminance: -0.16,
    blur: 0,
    contrast: -16,
  },
  {
    name: "avatar",
    src:
      "https://github.com/EXTC27/ai-pjt/blob/master/imgs/avatar.jpg?raw=true",
    hue: 156.1,
    saturation: 0.15,
    luminance: 0.02,
    blur: 0,
    contrast: 5,
  },
];
