export const filtersRef = [
  {
    name: "original",
    blur: 0,
    hue: 0,
    saturation: 0,
    luminance: 0,
    contrast: 0,
  },
  {
    name: "daily",
    hue: 0,
    saturation: 0.16,
    luminance: -0.0,
    blur: 0,
    contrast: 0,
  },
  {
    name: "light",
    hue: 0,
    saturation: 0.18,
    luminance: 0.08,
    blur: 0,
    contrast: 0,
  },
  {
    name: "plain",
    hue: 3.8,
    saturation: 0.08,
    luminance: 0.06,
    blur: 0,
    contrast: 0,
  },

  {
    name: "cream",
    hue: 0,
    saturation: 0.18,
    luminance: 0.19,
    blur: 0,
    contrast: 0,
  },

  {
    name: "pure",
    hue: 0,
    saturation: 0.04,
    luminance: 0.13,
    blur: 0,
    contrast: 0,
  },
  {
    name: "grayscale",
    hue: 0,
    saturation: -5,
    luminance: -0.03,
    blur: 0,
    contrast: 0,
  },
  {
    name: "BS",
    hue: 0,
    saturation: -0.13,
    luminance: 0.06,
    blur: 0,
    contrast: 0,
  },
  {
    name: "frozen",
    hue: 3.8,
    saturation: -0.38,
    luminance: 0.11,
    blur: 0,
    contrast: 0,
  },
  {
    name: "yummy",
    hue: 0,
    saturation: 0.38,
    luminance: -0.18,
    blur: 0,
    contrast: 0,
  },
  {
    name: "milk",
    hue: 0,
    saturation: -0.21,
    luminance: -0.01,
    blur: 0,
    contrast: 0,
  },
  {
    name: "crystal",
    hue: 0,
    saturation: 0.04,
    luminance: 0.03,
    blur: 0,
    contrast: 0,
  },
  {
    name: "cloud",
    hue: 0,
    saturation: 0,
    luminance: -0.13,
    blur: 0,
    contrast: 0,
  },
  {
    name: "mood",
    hue: 0,
    saturation: -0.04,
    luminance: -0.06,
    blur: 0,
    contrast: 0,
  },
  {
    name: "loveletter",
    hue: 6.4,
    saturation: 0.21,
    luminance: 0.06,
    blur: 0,
    contrast: 0,
  },
  {
    name: "baby",
    hue: 1.3,
    saturation: 0.21,
    luminance: 0.04,
    blur: 0,
    contrast: 0,
  },
  {
    name: "momo",
    hue: 0,
    saturation: 0.47,
    luminance: 0.13,
    blur: 0,
    contrast: 0,
  },
  {
    name: "winter",
    hue: 0,
    saturation: -0.34,
    luminance: 0.2,
    blur: 0,
    contrast: 26,
  },
  {
    name: "retro",
    hue: 6.4,
    saturation: -0.07,
    luminance: 0.19,
    blur: 0,
    contrast: 3,
  },
  {
    name: "alight",
    hue: 9.7,
    saturation: 0.46,
    luminance: 0.15,
    blur: 0,
    contrast: 8,
  },
  {
    name: "aurora",
    hue: 0,
    saturation: -0.09,
    luminance: 0.16,
    blur: 0,
    contrast: 23,
  },
  {
    name: "vintage",
    hue: 12.1,
    saturation: 0.12,
    luminance: 0.16,
    blur: 0,
    contrast: 28,
  },
  {
    name: "pretty",
    hue: 1.6,
    saturation: 0.1,
    luminance: 0.12,
    blur: 0,
    contrast: 35,
  },
  {
    name: "natural",
    hue: 0,
    saturation: 0.18,
    luminance: 0.2,
    blur: 0,
    contrast: 12,
  },
  {
    name: "blossom",
    hue: 2.4,
    saturation: -0.18,
    luminance: 0.11,
    blur: 0,
    contrast: 31,
  },
  {
    name: "drama",
    hue: 4.8,
    saturation: -3.38,
    luminance: 0.17,
    blur: 0,
    contrast: 17,
  },
  {
    name: "midnight",
    hue: 8.9,
    saturation: 0.66,
    luminance: -0.12,
    blur: 0,
    contrast: -15,
  },
  {
    name: "night",
    hue: 5.6,
    saturation: -0.39,
    luminance: -0.16,
    blur: 0,
    contrast: -16,
  },
  {
    name: "avatar",
    hue: 156.1,
    saturation: 0.15,
    luminance: 0.02,
    blur: 0,
    contrast: 5,
  },
  {
    name: "frozen",
    hue: 0,
    saturation: -0.12,
    luminance: 0.12,
    blur: 0,
    contrast: -1,
  },
];
// export const getFilters = () => {
//   return filtersRef;
// };
